name: gemini_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dash_chat_2: ^0.0.21
  flutter:
    sdk: flutter
  flutter_gemini:
    git:
      url: https://github.com/AkhmadRamadani/flutter_gemini.git
      ref: master
  flutter_launcher_icons: ^0.14.4
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
